apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scrapy-ingress
  namespace: scrapy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  {{- if .Values.ingressClassName}}
  ingressClassName: {{ .Values.ingressClassName }}
  {{- end}}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scrapyd-web-svc
            port:
              number: 80
