apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: scrapy
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongo.storageClassName | default "manual" }}
  hostPath:
    path: /mnt/data/mongo
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: {{ .Values.mongo.storageClassName | default "manual" }}
---
