FROM python:3.10-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install git -y

ADD . /app
WORKDIR /app

COPY requirements.txt .
COPY scrapydweb_settings_v10.py .

RUN apt-get update && \ 
  apt-get install -y git && \
  pip3 install -U git+https://github.com/my8100/scrapydweb.git && \
  apt-get remove -y git

RUN pip3 install -r requirements.txt

CMD scrapydweb